### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'mylist.txt'

### ISSUE THREAD

**Issue by zMrKrabz** [WyattBlue/jumpcutterV2#3]
I installed the program, and I tried to process a video of 1 hour 17min length. I got this error in the end. How would I fix this? On windows 10 machine

**Comment by WyattBlue** [comment]
Here a few things that can cause your problem:

### Number 1: You need to have ffmpeg
ffmpeg is a command line program that processes videos. 

Check if you have it by running this command 
```terminal
 $ ffmpeg -version
```

If not, download it with [choco](https://chocolatey.org/install) or something

```terminal
 $ choco install ffmpeg
```

### Number 2: You need to have a 64-bit version of python 3
Honestly just redownload python from the official site. 
https://www.python.org/
There's no point checking if it's not 64 bit or too old, since there's no harm redownloading it.

**Comment by zMrKrabz** [comment]
Hmm, reinstalling python, I now get `ModuleNotFoundError: No module named 'cv2'`. I managed to reproduce this issue with my friend as well.

**Comment by flyingzambie** [comment]
Did you run pip3 install -r requirements.txt ?

**Comment by zMrKrabz** [comment]
Yup

**Comment by flyingzambie** [comment]
try pip3 install opencv-python, does it do anything or does it say something like opencv installed?

**Comment by mlinaje** [comment]
I'm having the same issue with "mylist.txt' in windows 10 (FileNotFoundError)
In WSL2 not working due to other error: "python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime' Segmentation fault (core dumped)

For the windows powershell I use:

Number 1: You need to have ffmpeg
ffmpeg installed and tested with "ffmpeg -version". I use it regularly.

Number 2: You need to have a 64-bit version of python 3
Tested with this method and I'm using 64 bits in windows and WSL2:
https://www.scivision.dev/python-check-32-64-bit/
(Anyway I reinstalled the very lastest version, as I was in 3.8.2, 3.8.4 now)

I'm pretty sure the problem could be: 
generateFile = "for f in ./{}/*.mp4; do echo \"file '$f'\" >> mylist.txt; done".format(
    TEMP_FOLDER
)

**Comment by mlinaje** [comment]
Thanks for your work. I just made some little improvements mainly related to files and the OS.
Just let me know if you prefer some kind of pull request...
Best Regards,

`import glob
import sys
import os
import subprocess
import argparse
from shutil import rmtree
from fastVideo import fastVideo
from fasterVideo import fasterVideo

TEMP_FOLDER = ".TEMP_LONG"
if os.path.exists(TEMP_FOLDER):
	rmtree(TEMP_FOLDER)

def str2bool(v):
    if isinstance(v, bool):
       return v
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')

parser = argparse.ArgumentParser()
parser.add_argument("videoFile", help="the path to the video file you want modified.")
parser.add_argument(
    "-v",
    "--videoSpeed",
    type=float,
    default=1.0,
    help="the speed that the video plays at.",
)
parser.add_argument(
    "--silentSpeed",
    "-s",
    type=float,
    default=99999,
    help="the speed that silent frames should be played at.",
)
parser.add_argument(
    "--silentThreshold",
    "-t",
    type=float,
    default=0.04,
    help="the volume that frames audio needs to surpass to be sounded. It ranges from 0 to 1.",
)
parser.add_argument(
    "--frameMargin",
    "-m",
    type=int,
    default=4,
    help="tells how many frames on either side of speech should be included.",
)
parser.add_argument(
    "--splitDuration",
    "-d",
    type=int,
    default=1800,
    help="tells how many seconds should the video split chunks be, \
        use lower values if system has low ram, default 1800 (30 minutes).",
)
parser.add_argument(
    "--open", 
    "-o", 
    type=str2bool, 
    nargs='?', 
    const=True, 
    default=False,
    help="open file after processing is complete. Accepts boolean as input",
)
args = parser.parse_args()

videoFile = args.videoFile

try:
    os.mkdir(TEMP_FOLDER)
except OSError:
    rmtree(TEMP_FOLDER)
    os.mkdir(TEMP_FOLDER)

# splitting
filename, filetype = os.path.splitext(videoFile)
splitVideo = 'ffmpeg -i "{}" -acodec copy -f segment -segment_time {} -vcodec copy -reset_timestamps 1 -map 0 {}/%d{}'.format(
    videoFile, args.splitDuration, TEMP_FOLDER, filetype
)
subprocess.call(splitVideo, shell=True)


# processing
if args.silentSpeed == 99999 and args.videoSpeed == 1.0:
    for files in os.listdir(TEMP_FOLDER):
        videoPath = os.path.join('{}', '{}').format(TEMP_FOLDER, files)
        fasterVideo(videoPath, args.silentThreshold, args.frameMargin)
        os.remove(videoPath)
else:
    for files in os.listdir(TEMP_FOLDER):
        videoPath = os.path.join('{}', '{}').format(TEMP_FOLDER, files)
        fastVideo(
            videoPath,
            args.silentSpeed,
            args.videoSpeed,
            args.silentThreshold,
            args.frameMargin,
        )
        os.remove(videoPath)

MyFile=open('mylist.txt','w')

for item in glob.glob(os.path.join('.', TEMP_FOLDER, '*.mp4')):
	MyFile.write("file '")
	MyFile.write(item)
	MyFile.write("'\n")

MyFile.close()


concatVideo = ["ffmpeg", "-f", "concat", "-safe", "0", "-i", "mylist.txt", "-c", "copy", filename + "_faster.mp4"]
subprocess.call(concatVideo)

os.remove('mylist.txt'))

outFile = filename + "_faster.mp4"

if not os.path.isfile(outFile):
    raise IOError(f"the file {outFile} was not created")

if args.open:
    try:  # should work on Windows
        os.startfile(outFile)
    except AttributeError:
        try:  # should work on MacOS and most linux versions
            subprocess.call(["open", outFile])
        except:
            try: # should work on WSL2
                subprocess.call(["cmd.exe", "/C", "start", outFile])
            except:
                print("could not open output file")

rmtree(TEMP_FOLDER)
`

**Comment by mlinaje** [comment]
Just remove the last ) in
os.remove('mylist.txt'))

(I was testing the file content and I didn't reactivate this part until the end of the tests).
Best,

**Comment by flyingzambie** [comment]
@mlinaje if you want to put up a pull request it would be great! Tho we have mostly moved over to auto-editor, and we are using a much better implementation there now. https://github.com/WyattBlue/auto-editor

**Comment by mlinaje** [comment]
Just did it. Testing on a proper Linux system and ESL, WSL2 would be great (I have problem running many python scripts in WSL2 that are general and not specific for jumcutterv2).

I'm also "playing" with autoeditor for the last 2 days, but I have audio/vido sync issue. I will test more an open an issue in the other github with the tests.

Best to you and thanks for sharing the code ;-)
